name: Build EmulationStation

on:
  push:
    branches: [ "main", "master" ]

permissions:
  contents: write
  
env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:24.04
    
    steps:
      - name: Install compiling tools
        run: |
          apt-get -y update
          apt-get -y install git libsdl2-dev libsdl2-mixer-dev libfreeimage-dev libfreetype6-dev \
                             libcurl4-openssl-dev rapidjson-dev libasound2-dev libyuv-dev libcec-dev \
                             libpugixml-dev build-essential libboost-all-dev cmake libint-dev gettext \
                             locales libavcodec-dev libavfilter-dev fonts-droid-fallback libvlc-dev \
                             libvlccore-dev vlc-bin
          apt-get -y clean
          rm -rf /var/lib/apt/lists/*
          sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
          locale-gen

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
           submodules: recursive
              
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
